interface DictionaryInterface {
   
   lookup(string str, string src_lang, string dest_lang) : string |array|ResultsIterator; 

   getDictionaryLanguages() : array;
}

class RestClient {

   static createRestClient(ClassID $id) : mixed
}

class PonsDictionary extends  RestClient implements DictionaryInterface {

   __construct(PonsConfig c = new PonsConfig)

   getDictionaryLanguages() : array 

   getDictionaryForLanguages(string lang) : array

   lookup(string text, string src, string dest) : ResultsIterator
}
