interface SentenceFetchInterface  { 

   fetch(string word, int count=3) : ResultsIterator;
}

class RestClient {

   static createRestClient(ClassID $id) : mixed
}

class UniLeipzigSentenceFetcher extends RestClient implements SentenceFetchInterface {

   __construct( UniLeipzigConfig c = new UniLeipzigConfig() )
   
   fetch(string word, int count=3) :  ResultsIterator
}
